name: Build vpc infrastructure

on:
    pull_request:
        branches: [main]
        paths:
            - 'tools/cluster/*'
    push:
        branches: [main]
        paths:
            - 'tools/cluster/*'
    

jobs:
    build:
        name: Build vpc infrastructure
        runs-on: [self-hosted, pulumi]
    
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                path: ${{ env.SRC_PREFIX }}

            - name: Install Dependencies
              working-directory: ./tools/cluster
              run: |
                npm install

              # It seems that the runner does not load .bashrc, duh
              # so if we have an executable in a weird path (like pulumi) access via absolute path
            - name: Pulumi build
              working-directory: ./tools/cluster
              env:
                PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
              run: |
                /.pulumi/bin/pulumi stack select BOM-DEMO/cluster/dev
                /.pulumi/bin/pulumi up -y