name: Build vpc infrastructure

on:
    pull_request:
        branches: [main]
        paths:
            - 'tools/vpc/*'
    push:
        branches: [main]
        paths:
            - 'tools/vpc/*'
    

jobs:
    build:
        name: Build vpc infrastructure
        runs-on: [self-hosted, pulumi]
    
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                path: ${{ env.SRC_PREFIX }}

              # TODO: make this general for all folders (except olufi)
            - name: Change Directory
              run: |
                cd tools/vpc

            - name: Install Dependencies
              run: |
                npm install

              # It seems that the runner does not load .bashrc, duh
              # so if we have an executable in a weird path (like pulumi) access via absolute path
            - name: Pulumi build
              env:
                PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
              run: |
                /.pulumi/bin/pulumi stack select BOM-DEMO/vpc/dev
                /.pulumi/bin/pulumi up -y