name: Build vpc infrastructure

on:
    pull_request:
        branches: [main]
        paths:
            - 'tools/vpc/*'
    push:
        branches: [main]
        paths:
            - 'tools/vpc/*'
        
jobs:
    build:
        name: Build vpc infrastructure
        runs-on: [self-hosted, pulumi]
    
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                path: ${{ env.SRC_PREFIX }}

            - name: Pulumi build
              run: |
                whoami
                cd tools/vpc
                sudo pulumi up -y