name: Build vpc infrastructure

on:
    pull_request:
        branches: [main]
        paths:
            - 'tools/vpc/*'
    push:
        branches: [main]
        paths:
            - 'tools/vpc/*'
     
env:
    PULUMI_ACCESS_TOKEN: ${{ env.PULUMI_ACCESS_TOKEN }}

jobs:
    build:
        name: Build vpc infrastructure
        runs-on: [self-hosted, pulumi]
    
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                path: ${{ env.SRC_PREFIX }}

              # It seems that the runner does not load .bashrc, duh
              # so if we need to use an executable, we need absolute path
            - name: Pulumi build
              run: |
                whoami
                ls
                cd tools/vpc
                /.pulumi/bin/pulumi up -y